version: '2'
services:
  nginx-proxy:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    container_name: nginx-proxy
    ports:
      - "8889:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - authproxy-net

networks:
  authproxy-net:
    driver: bridge


    
#8ac7e42376e0   authproxy_default       bridge    local
#4de0db03c13d   awxcompose_default      bridge    local
#c341a26544f9   keycloak_default        bridge    local
#68f996b0fd25   netbox-docker_default   bridge    local



#  whoami:
#    image: jwilder/whoami
#    environment:
#      - VIRTUAL_HOST=whoami.local
