version: '2'
services:
  nginx-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: garnser/nginx-oidc-docker-proxy
    container_name: nginx-proxy
    ports:
      - "10080:80"
      - "10443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d:ro
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    networks:
      - authproxy-net

networks:
  authproxy-net:
    driver: bridge


    
#8ac7e42376e0   authproxy_default       bridge    local
#4de0db03c13d   awxcompose_default      bridge    local
#c341a26544f9   keycloak_default        bridge    local
#68f996b0fd25   netbox-docker_default   bridge    local



#  whoami:
#    image: jwilder/whoami
#    environment:
#      - VIRTUAL_HOST=whoami.local
